Answer to Q.No 1:

Numpy is a library for numerical and scientific computations in python. It offers fast and efficient operations on data sets, especially for tasks involving arrays and matrices making it an ideal choice for data analyis.

Answer to Q.No 2:

np.mean() Computes arithmetic mean along an axis.
ap.average() It allows weighted averages, where each value can have different importance.

Example:


In [ ]:
import numpy as np
data = np.array([1, 2, 3, 4])
print(np.mean(data))
print(np.average(data))


2.5
2.5


Answer to Q.No 3:

1D Array: Using [::-1] would be used to reverse numpy array.
2D Array : Using np.flip() or specify axes with np.flipud() (up-down) and np.fliplr(left-right).

Example:


In [ ]:
arr = np.array([[1, 2], [3, 4]])
print(np.flip(arr, axis=0))


[[3 4]
 [1 2]]


Answer to Q.No 4:

Use .dtype to find the data type in numpy array. Data types help to manage memory and optimize performance.

Answer to Q.No 5:

ndarray is the primary data structure in numpy, optimized for numerical operations, supporting multidimensional arrays and providing faster computations than python lists.

Answer to Q.No 6:

Numpy array are faster than python lists for numerical operations because they use contiguous memory blocks and leverage C-based operations.


Answer to Q.No.7:

vstack(): vertically stacks arrays.
hstack(): horizontally stacks arrays.

Example:


In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.vstack((a, b)))


[[1 2]
 [3 4]]


Answer to Q.No 8:

fliplr() : Flip arrays left to right.
flipud() : Flip arrays up to down.

Answer to Q. No 9:

Splits an array into sub-arrays. Handles uneven splits by creating sub-arrays of different sizes.

Answer to Q.No. 10:

Vectorization and broadcasting allow operations on arrays without explicit loops, making computation faster.

Practical Questions:

Answer to Q.No. 1:

In [ ]:
arr = np.random.randint(1, 100, (3, 3))
print(arr.T)

[[83  1 88]
 [60 26 86]
 [ 9 48 82]]


Answer to Q.No 2:


In [ ]:
import numpy as np
arr = np.arange(10)
arr_2x5 = arr.reshape(2, 5)
arr_5x2 = arr.reshape(5, 2)
print(arr_2x5)
print(arr_5x2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Answer to Q.No: 3


In [ ]:
arr_4x4 = np.random.rand(4, 4)
arr_with_border = np.pad(arr_4x4, pad_width=1, mode='constant', constant_values=0)
print("Original 4x4 Array:\n", arr_4x4)
print("Array with a Border of Zeros (6x6):\n", arr_with_border)


Original 4x4 Array:
 [[0.28885043 0.34557731 0.74004581 0.59058913]
 [0.7679681  0.02969017 0.80643338 0.04853989]
 [0.22656799 0.62223246 0.38317704 0.34298684]
 [0.14269327 0.74586544 0.9083428  0.81464619]]
Array with a Border of Zeros (6x6):
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.28885043 0.34557731 0.74004581 0.59058913 0.        ]
 [0.         0.7679681  0.02969017 0.80643338 0.04853989 0.        ]
 [0.         0.22656799 0.62223246 0.38317704 0.34298684 0.        ]
 [0.         0.14269327 0.74586544 0.9083428  0.81464619 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Answer to Q.No. 4:


In [ ]:
arr_step_5 = np.arange(10, 61, 5)
print("Array from 10 to 60 with a step of 5:\n", arr_step_5)


Array from 10 to 60 with a step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


Answer to Q.No 5:


In [ ]:
arr_strings = np.array(['python', 'numpy', 'pandas'])
upper_case = np.char.upper(arr_strings)
lower_case = np.char.lower(arr_strings)
title_case = np.char.title(arr_strings)
print("Uppercase:\n", upper_case)
print("Lowercase:\n", lower_case)
print("Title Case:\n", title_case)


Uppercase:
 ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:
 ['python' 'numpy' 'pandas']
Title Case:
 ['Python' 'Numpy' 'Pandas']


Answer to Q.No 6:


In [ ]:
arr_words = np.array(['python', 'numpy'])
spaced_arr = np.array([' '.join(list(word)) for word in arr_words])
print("Array with spaces between characters:\n", spaced_arr)


Array with spaces between characters:
 ['p y t h o n' 'n u m p y']


Answer to Q.No 7:


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("Element-wise Addition:\n", a + b)
print("Element-wise Subtraction:\n", a - b)
print("Element-wise Multiplication:\n", a * b)
print("Element-wise Division:\n", a / b)


Element-wise Addition:
 [[ 6  8]
 [10 12]]
Element-wise Subtraction:
 [[-4 -4]
 [-4 -4]]
Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Element-wise Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


Answer to Q.No 8:


In [ ]:
identity_matrix = np.eye(5)
diagonal_elements = np.diag(identity_matrix)
print("5x5 Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:\n", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements:
 [1. 1. 1. 1. 1.]


Answer to Q.No 9:


In [ ]:
arr_random = np.random.randint(0, 1000, 100)
primes = [num for num in arr_random if num > 1 and all(num % i != 0 for i in range(2, int(num**0.5) + 1))]
print("Array of Random Integers:\n", arr_random)
print("Prime Numbers in Array:\n", primes)


Array of Random Integers:
 [229 678 154 873 975 311  23 828 529 412 848 775 698 307 174 882 421 446
 909 684 344 362 774 780 867 993  89 568 611 331 645 492 982 327 357 930
 444 248 762 432 980 951 990  63 204 165 982 291 253 631 896 956 881 902
 877 465 415 412 451  74 888 204 740 652 645 384 690 520  90 674 297 602
 840 571 826 280 870 626 960 296 539 594 264 840 791 989 969  63 419  89
 296 629 704 160 843 466  42 315 927  65]
Prime Numbers in Array:
 [229, 311, 23, 307, 421, 89, 331, 631, 881, 877, 571, 419, 89]


Answer to Q.No 10:


In [ ]:
daily_temps = np.random.randint(15, 35, 30)  # 30 days representing daily temperatures
# Change the reshape to have a number of rows that evenly divides 30
# For example, using 5 rows and 6 columns (5 * 6 = 30)
weekly_avg = daily_temps.reshape(5, -1).mean(axis=1)
print("Daily Temperatures:\n", daily_temps)
print("Weekly Averages:\n", weekly_avg)


Daily Temperatures:
 [26 25 16 29 19 24 22 16 18 26 27 31 22 27 22 30 18 15 31 20 17 20 26 30
 27 21 27 32 29 23]
Weekly Averages:
 [23.16666667 23.33333333 22.33333333 24.         26.5       ]
